import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [val, setVal] = useState("")
  const [value, setValue] = useState(0)
  const [fact, setFact] = useState("")
  const changeHandler = (a) =>{
    setVal(a)
  }
  const btnClick = async () =>{
    let data = await fetch(`http://numbersapi.com/${value}/${val}?json`)
    let json = await data.json()
    console.log(json)
    setFact(json.text)
  }
  return (
    <>
      <Head>
        <title>Number Facts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="text-gray-600 body-font relative">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-col text-center w-full mb-12">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Amazing Facts About Numbers</h1>
            </div>
            <div className="lg:w-1/2 md:w-2/3 mx-auto">
              <div className="flex flex-wrap -m-2">
                <div className="p-2 w-full">
                  <div className="relative">
                    <label for="name" className="leading-7 text-sm text-gray-600">Number</label>
                    <input type="number" id="number" name="number" className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" value={value} onChange={e => setValue(e.target.value)}/>
                  </div>
                </div>
                <div className='p-2 w-full'>
                  <input type="radio" id="num" name="val" value="trivia" onClick={()=>changeHandler("trivia")}/>
                    <label for="vehicle1"> Fact about this number</label><br/>
                  <input type="radio" id="year" name="val" value="year" onClick={()=>changeHandler("year")}/>
                  <label for="vehicle2"> Fact about this year</label><br/>
                  <input type="radio" id="maths" name="val" value="math" onClick={()=>changeHandler("math")}/>
                  <label for="vehicle2"> Fact about this in maths</label><br/>
                  <input type="radio" id="date" name="val" value="date" onClick={()=>changeHandler("date")}/>
                  <label for="vehicle3"> Fact about this date</label><br/><br/><br/>
                </div>
                <div className="p-2 w-full">
                  <button className="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" onClick={()=>btnClick()}>Load Fact</button>
                </div>
                <div className="p-2 w-full pt-8 mt-8 border-t border-gray-200 text-center">
                  <h1>{ fact}</h1>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
